backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "المقالات"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "تاريخ النشر", name: "date", widget: "datetime" }
      - { label: "الملخص", name: "summary", widget: "text" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
